comments/urls.py
from django.urls import path

from .views import CommentCreateView

urlpatterns = [
    path('create/<str:content_type>/<int:object_id>/', CommentCreateView.as_view(), name='comment-create')
]

app_name = 'comments'

djangochannels/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('posts.urls')),
    path('comments/', include('comments.urls', namespace='comments'))
]

posts/urls.py
from django.urls import path

from .views import PostListView, PostDetailView

urlpatterns = [
    path('posts/', PostListView.as_view(), name='posts'),
    path('posts/<str:post_slug>/', PostDetailView.as_view(), name='post')
]

comments/models.py
from django.db import models
from django.utils import timezone
from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes.fields import GenericForeignKey

from utils.default_user import User


class Comment(models.Model):

    author = models.ForeignKey(User, verbose_name='Автор комментария', on_delete=models.CASCADE)
    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    object_id = models.PositiveIntegerField()
    content_object = GenericForeignKey('content_type', 'object_id')
    text = models.TextField(verbose_name='Текст комментария')
    created_at = models.DateTimeField(editable=False)

    def __str__(self):
        return f"{self.id}"

    def save(self, *args, **kwargs):
        if not self.id:
            self.created_at = timezone.now()
        super().save(*args, **kwargs)

posts/models.py
from django.db import models
from django.contrib.contenttypes.fields import GenericRelation
from django.urls import reverse
from django.utils import timezone

from utils.default_user import User


class Post(models.Model):

    author = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Автор')
    title = models.CharField(max_length=255, verbose_name='Заголовок')
    slug = models.SlugField()
    content = models.TextField(verbose_name='Содержимое поста')
    created_at = models.DateTimeField(editable=False)
    updated_at = models.DateTimeField()
    comments = GenericRelation('comments.Comment')

    def save(self, *args, **kwargs):
        if not self.id:
            self.created_at = timezone.now()
        self.updated_at = timezone.now()
        return super().save(*args, **kwargs)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('post', kwargs={'post_slug': self.slug})

comments/forms.py
from django import forms

from .models import Comment


class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ['text']

comments/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib.contenttypes.models import ContentType
from django.contrib import messages
from django.http import HttpResponseRedirect
from django.views import View

from posts.models import Post

from .models import Comment
from .forms import CommentForm


class CommentCreateView(View):

    @staticmethod
    def post(request, *args, **kwargs):
        form = CommentForm(request.POST or None)
        ct = ContentType.objects.get(model=kwargs['content_type'])
        model = ct.model_class().objects.get(pk=kwargs['object_id'])
        if form.is_valid():
            new_comment = form.save(commit=False)
            new_comment.author = request.user
            new_comment.text = form.cleaned_data['text']
            new_comment.content_object = model
            new_comment.save()
            return HttpResponseRedirect(model.get_absolute_url())
        messages.add_message(request, messages.ERROR, 'Не удалось оставить комментарий')
        return HttpResponseRedirect(model.get_absolute_url())

posts/views.py
from django.views.generic import ListView, DetailView

from .models import Post

from comments.forms import CommentForm

class PostListView(ListView):

    model = Post
    template_name = 'posts.html'
    context_object_name = 'posts'


class PostDetailView(DetailView):

    model = Post
    template_name = 'post_detail.html'
    context_object_name = 'post'
    slug_url_kwarg = 'post_slug'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = CommentForm(self.request.POST or None)
        return context

posts/templates/post_detail.html
{% extends 'posts.html' %}
{% load crispy_forms_tags %}
{% block content %}
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
      <li class="breadcrumb-item active" aria-current="page"><a href="{% url 'posts' %}">Назад к постам</a></li>
  </ol>
</nav>
    <hr>
    <h4 class="text-center">{{ post.title }}</h4>
    <small>опубликовано: {{ post.created_at|date:"Y-m-d" }}</small>
    <br><br>
    <p>{{ post.content|safe }}</p>
    <hr>
    <p><strong>Комментарии</strong>: <span class="badge rounded-pill bg-dark">{{ post.comments.count }}</span></p>
    <br>
    <div class="row">
        {% for comment in post.comments.all %}
            <div class="col-md-12 mt-3 mb-3">
                <p><strong>{{ comment.author.username }}</strong> | <small>опубликовано:{{ comment.created_at|date:"Y-m-d" }}</small></p>
                <p>{{ comment.text }}</p>
            </div>
        {% endfor %}
    </div>
    <hr>
    {% if request.user.is_authenticated %}
    <form action="{% url 'comments:comment-create' content_type="post" object_id=post.id %}" method="POST">
        {% csrf_token %}
        {{ form|crispy }}
        <br>
    <input class="btn btn-primary" type="submit" value="Отправить">
    </form>
    {% else %}
        <p class="text-center">Оставлять комментарии могут только авторизованные пользователи</p>
    {% endif %}
{% endblock content %}

posts/templates/posts.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">

</head>
<body>
<div class="container mt-3">
{% block content %}
<h3>Посты</h3>
<hr>
    <div class="row">
        {% for post in posts %}
            <div class="col-md-4">
                <h5>{{ post.title }}</h5>
                <p><small>опубликовано: {{ post.created_at|date:"Y-m-d" }}</small></p>
                <a href="{% url 'post' post_slug=post.slug %}" style="text-decoration: none; color:white">
                    <button class="btn btn-primary">Читать</button>
                </a>
            </div>
        {% endfor %}
    </div>
{% endblock content %}
</div>
</body>
</html>